version: '3.4'
# Aqui configuramos por lo general las variables de entorno
services:
  catalogdb:
    container_name: catalogdb
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=CatalogDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
        - postgres_catalog:/var/lib/postgresql/data/
  